'use client';
import { FC } from 'react';

// NEXT
import type { Metadata } from 'next';
import '@/assets/css/globals/globals.css';
import '@/assets/css/globals/normalize.css';
import { poppins } from '@/assets/fonts/fonts';
import { stateDarkMode } from '@/store';

// META
const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// TS
interface Props {
  children : React.ReactNode
}

const RootLayout :FC<Props> = ({children}) => {

  const { isDarkMode } = stateDarkMode();

  return (
    <html lang="es">
      <body className={`${poppins.className} ${ isDarkMode ? 'dark body-dark' : 'body-light' }`}>
        {children}
      </body>
    </html>
  )
}

export default RootLayout;